apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-sgx-plugin
  namespace: kube-system
  labels:
    app: intel-sgx-plugin
spec:
  selector:
    matchLabels:
      app: intel-sgx-plugin
  template:
    metadata:
      labels:
        app: intel-sgx-plugin
    spec:
      serviceAccountName: sgx-extres-api
      initContainers:
      - name: intel-sgx-initcontainer
        image: praneja/sgx-resource-manager:0.1
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      containers:
      - name: intel-sgx-plugin
        image: praneja/intel-sgx-plugin:0.1
        securityContext:
          readOnlyRootFilesystem: true
        imagePullPolicy: Always
        volumeMounts:
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
        - name: sgxdevices
          mountPath: /dev/sgx
          readOnly: true
        - name: sgx-enclave
          mountPath: /dev/sgx/enclave
          readOnly: true
        - name: sgx-provision
          mountPath: /dev/sgx/provision
          readOnly: true
      volumes:
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: sgxdevices
        hostPath:
          path: /dev/sgx
          type: DirectoryOrCreate
      - name: sgx-enclave
        hostPath:
          path: /dev/sgx/enclave
          type: CharDevice
      - name: sgx-provision
        hostPath:
          path: /dev/sgx/provision
          type: CharDevice
